import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '../globals.css';
import nextAuthOptions from '@FsdApp/auth/config/next-auth';
import AuthProvider from '@FsdApp/auth/providers/AuthProvider';
import NextAuthProvider from '@FsdApp/auth/providers/NextAuthProvider';
import I18nProvider from '@FsdApp/i18n/providers/I18nProvider';
import MockServerInit from '@FsdApp/mock/inits/MockServerInit';
import ReactQueryProvider from '@FsdApp/react-query/providers/ReactQueryProvider';
import StoreProvider from '@FsdApp/store/providers/StoreProvider';
import { Locale } from '@FsdShared/libs/i18n';
import { getServerSession } from 'next-auth';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params,
  mainModal,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: string }>;
  mainModal: React.ReactNode;
}>) {
  const session = await getServerSession(nextAuthOptions);
  const { lang } = await params;

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <StoreProvider>
          <ReactQueryProvider>
            <NextAuthProvider session={session}>
              <AuthProvider>
                <MockServerInit>
                  <I18nProvider locale={lang as Locale}>
                    {children}
                    {mainModal}
                  </I18nProvider>
                </MockServerInit>
              </AuthProvider>
            </NextAuthProvider>
          </ReactQueryProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
